# Generated by Django 4.1 on 2022-08-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
